#!/usr/bin/env python3
"""Fetch every file in the LAI 2026 mini-matter index and bundle into files.js."""
import json
import urllib.request
import urllib.parse

INDEX = "https://lai2026.jackcushman.org/materials/index.json"


UA = "lai-matter-browser/1.0 (+workshop bundle generator)"


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main():
    index = json.loads(fetch(INDEX))
    files = {}
    for entry in index["files"]:
        path = entry["path"]
        url = entry["url"]
        mime = entry.get("mime_type", "")
        if mime.startswith("text/"):
            try:
                body = fetch(url).decode("utf-8")
            except UnicodeDecodeError:
                body = fetch(url).decode("utf-8", errors="replace")
            files[path] = body
            print(f"  ok  {path}  ({len(body)} chars)")
        else:
            files[path] = f"[binary file: {mime}, {entry['size']} bytes — not bundled]"
            print(f"  skip {path}  (binary {mime})")

    payload = {
        "matter": index.get("matter"),
        "base_url": index.get("base_url"),
        "index": index["files"],
        "toc": index.get("toc", []),
        "files": files,
    }
    with open("files.js", "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_files_js.py — do not edit by hand.\n")
        f.write("window.LAI_MATTER = ")
        json.dump(payload, f, ensure_ascii=False)
        f.write(";\n")
    print(f"\nwrote files.js with {len(files)} file bodies")


if __name__ == "__main__":
    main()
